---
- name: install zabbix agent on Linux
  hosts: all
  become: yes
  gather_facts: true


  tasks:


  - name: disable SElinux
      selinux:
        state: disabled

  - name: download zabbix centOS 9 rpm file
      yum:
        name: "https://repo.zabbix.com/zabbix/6.0/rhel/9/x86_64/zabbix-agent2-6.0.25-release1.el9.x86_64.rpm"
        validate_certs: no

  - name: upgrade all packages
      yum: name=* state=latest

  - name: install zabbix-agent 6.x for centOS 9
      yum: 
        name: zabbix-agent
        state: latest

  - name: Copy zabbix_agentd.conf file with owner and permissions
      ansible.builtin.copy:
        src: zabbix_agentd.conf
        dest: /etc/zabbix/zabbix_agentd.conf


  #####     CONFIGURE     #####    

 
  - name: create conf file
    become: yes
    template:
      src: zabbix_agentd.conf.j2
      dest: /etc/zabbix/zabbix_agentd.conf
      mode: 0755
  
  - name: permit traffic in zabbix agent ports
    become_user: root
    become: yes
    shell: firewall-cmd --permanent --add-port=10050-10051/tcp --zone=public
    when: 
      ansible_os_family in ['RedHat', 'Debian', 'Suse']
    ignore_errors: yes

  - name: reload firewalld
    become_user: root
    become: yes
    shell: firewall-cmd --reload
    when: 
      ansible_os_family in ['RedHat', 'Debian', 'Suse'] 
    ignore_errors: yes


 #####     START      #####

   - name: Start service Zabbix Agent, if not started
     ansible.builtin.service:
       name: zabbix-agent
       state: started


#####     VERIFY      #####


  - name: checking pid file started
    stat:
      path: /var/run/zabbix/zabbix_agentd.pid
    register: check_pid_start

  - fail:
      msg: "service not started"
    when: check_pid_start.stat.exists != true


...
