---
- name: remove zabbix agent on Linux
  hosts: all
  become: true
  gather_facts: true

  tasks:

  - name: Uninstall zabbix-agent but keep its dependencies
    ansible.builtin.dnf:
      name: zabbix-agent
      state: absent
      autoremove: no

...
