---
- name: restart zabbix agent on unix
  hosts: all
  become: yes
  gather_facts: true
   

  tasks:

  - name: checking process zabbix
    shell: ps -ef | grep zabbix | grep -v grep | awk '{print $2}'
    register: ps_zabbix
   
  - name: kill zabbix processes
    become: yes
    shell: kill -TERM {{item}}
    with_items:
      - "{{ps_zabbix.stdout_lines}}"
    when: "{{ps_zabbix.stdout != ''}}" 
    ignore_errors: yes

  
#####     START      #####

  - name: Start Zabbix Agent - Linux Default
    service:
      name: zabbix-agent2
      state: started
    ignore_errors: yes
    

###### READ LOG     #######

  - name: Read /var/log/zabbix/zabbix_agent2.log
    ignore_errors: yes
    shell: "tail -n 20 /var/log/zabbix/zabbix_agent2.log"
    register: out_log
...
