---
- name: install zabbix agent on Linux
  hosts: all
  become: true
  gather_facts: true

  tasks:

  - name: Uninstall zabbix-agent but keep its dependencies
    ansible.builtin.dnf:
      name: zabbix-agent
      state: absent
      autoremove: no

  - name: Install zabbix centOS 9 rpm file
    ansible.builtin.dnf:
        name: "https://repo.zabbix.com/zabbix/6.0/rhel/9/x86_64/zabbix-agent-6.0.24-release1.el9.x86_64.rpm"
        state: present
        disable_gpg_check: true

  #- name: Upgrade all packages
  #  ansible.builtin.dnf:
  #    name: "*"
  #    state: latest

  #- name: Update zabbix-agent 6.x for centOS 9
  #  ansible.builtin.dnf:
  #    name: zabbix-agent
  #    state: latest
  #    update_only: yes


  #####     CONFIGURE     #####    

 
  - name: create conf file
    become: true
    ansible.builtin.template:
      src: template_zabbix_agentd.conf.j2
      dest: /etc/zabbix/zabbix_agentd.conf
      mode: 0755
  
  - name: permit traffic in zabbix agent ports
    become: true
    ansible.builtin.shell: firewall-cmd --permanent --add-port=10050-10051/tcp --zone=public
    
  - name: reload firewalld
    become: true
    ansible.builtin.shell:  firewall-cmd --reload
    

 #####     START      #####

  - name: Start service Zabbix Agent, if not started
    ansible.builtin.service:
       name: zabbix-agent
       state: started


#####     VERIFY      #####


  - name: checking pid file started
    ansible.builtin.stat:
      path: /var/run/zabbix/zabbix_agentd.pid
    register: check_pid_start

  - name: fail message
    ansible.builtin.fail:
      msg: "service not started"
    when: check_pid_start.stat.exists != true


...
